# Generated by Django 4.2.3 on 2023-07-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.course')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTestes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('post', 'post'), ('post', 'post')], max_length=20)),
                ('param1', models.CharField(blank=True, max_length=30, null=True)),
                ('param2', models.CharField(blank=True, max_length=30, null=True)),
                ('param3', models.CharField(blank=True, max_length=30, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, default=200, null=True)),
                ('is_list', models.BooleanField(default=False)),
                ('is_contains', models.CharField(blank=True, max_length=100, null=True)),
                ('key_name', models.CharField(blank=True, max_length=30, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testes')),
            ],
        ),
    ]
