# Generated by Django 4.2.3 on 2023-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_unittestes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittestes',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unittestes',
            name='method',
            field=models.CharField(choices=[('post', 'post'), ('get', 'get')], max_length=20),
        ),
    ]
