# Generated by Django 4.2.3 on 2023-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_unittestes_key_name1_unittestes_key_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittestes',
            name='status_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
