# Generated by Django 4.2.3 on 2023-07-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_unittestes_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittestes',
            name='key_name2',
        ),
    ]
