# Generated by Django 4.2.3 on 2023-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_remove_unittestes_key_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestes',
            name='param4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
