# Generated by Django 4.2.3 on 2023-07-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_alter_unittestes_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittestes',
            name='json',
        ),
    ]
