# Generated by Django 4.2.3 on 2023-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_remove_unittestes_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestes',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
