# Generated by Django 4.2.3 on 2023-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_unittestes_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestes',
            name='key',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unittestes',
            name='param',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
