# Generated by Django 4.2.3 on 2023-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_unittestes_key_unittestes_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittestes',
            name='key_name',
        ),
        migrations.RemoveField(
            model_name='unittestes',
            name='key_name1',
        ),
        migrations.RemoveField(
            model_name='unittestes',
            name='param1',
        ),
        migrations.RemoveField(
            model_name='unittestes',
            name='param2',
        ),
        migrations.RemoveField(
            model_name='unittestes',
            name='param3',
        ),
        migrations.RemoveField(
            model_name='unittestes',
            name='param4',
        ),
        migrations.AddField(
            model_name='unittestes',
            name='is_contain',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
