# Generated by Django 4.2.3 on 2023-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_remove_unittestes_key_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittestes',
            name='is_contains',
        ),
        migrations.AddField(
            model_name='unittestes',
            name='login_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unittestes',
            name='login_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
