# Generated by Django 4.2.3 on 2023-10-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_remove_unittestes_is_contains_unittestes_login_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittestes',
            name='login_json',
        ),
        migrations.RemoveField(
            model_name='unittestes',
            name='login_url',
        ),
    ]
