# Generated by Django 5.0 on 2024-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_problem_probleminput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminput',
            name='input',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
