# Generated by Django 5.0 on 2024-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_alter_probleminput_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminput',
            name='input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
